language: node_js
node_js:
  - node

dist: bionic
sudo: false

script:
  - npm run lint
  - npm test

branches:
  except:
    - /^v\d+\.\d+\.\d+$/
    - gh-pages

notifications:
  webhooks: http://webhook.hakatashi.com/travis
